name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.grist }}
    strategy:
      matrix:
        ruby:
          - '2.7.5'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: grist/setup-grist@v1
      with:
        ruby-version: ${{ matrix.grist }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
