name: Ruby

on:
  push:
    branches:
      - main
      - develop

  pull_request:

env:
  GRIST_API_URL: "http://localhost:8484"
  GRIST_API_KEY: "abc"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.0'
          - '3.2.2'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Execute specs
        run: bundle exec rspec